management:
  endpoint:
    health:
      enabled: false
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
#    max-treads: 1024
#    tomcat:
#        max-threads: "${server.max-treads}"
#    undertow:
#        worker-threads: "${server.max-treads}"
#    jetty:
#        acceptors: "${server.max-treads}"
  port: 11515
  address: 127.0.0.1

spring:
  custom:
    datasource:
      hikari:
        connectionTestQuery: SELECT 1
        connectionTimeout: 90000
        idleTimeout: 150000
        minimumPoolSize: 0
        maximumPoolSize: 200
        minimumIdle: 0
        poolName: dbpool
      type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      indent_output: true
#  h2:
#    console:
#      enaabled: false
#      path: /h2

#spring.banner.image.bitdepth: 8
#spring.banner.image.pixelmode: block

spring.h2.console.enabled: false
