spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
    cache.cachecontrol.max-age: 0
  main:
    lazy-initialization: true

server.max-treads: 1024
server.tomcat.max-threads: "${server.max-treads}"
server.undertow.worker-threads: "${server.max-treads}"
server.jetty.acceptors: "${server.max-treads}"